namespace MarkEmbling.PostcodesIO {
    public class LatLonBulkLookupResult {
        /*
{
    "status": 200,
    "result": [
        {
            "query": {
                "longitude": "0.629834723775309",
                "latitude": "51.7923246977375"
            },
            "result": [
                {
                    "postcode": "CM8 1EF",
                    "quality": 1,
                    "eastings": 581461,
                    "northings": 213679,
                    "country": "England",
                    "nhs_ha": "East of England",
                    "longitude": 0.629834723775309,
                    "latitude": 51.7923246977375,
                    "parliamentary_constituency": "Witham",
                    "european_electoral_region": "Eastern",
                    "primary_care_trust": "Mid Essex",
                    "region": "East of England",
                    "lsoa": "Braintree 017F",
                    "msoa": "Braintree 017",
                    "nuts": null,
                    "incode": "1EF",
                    "outcode": "CM8",
                    "distance": 0,
                    "admin_district": "Braintree",
                    "parish": "Witham",
                    "admin_county": "Essex",
                    "admin_ward": "Witham South",
                    "ccg": "NHS Mid Essex",
                    "codes": {
                        "admin_district": "E07000067",
                        "admin_county": "E10000012",
                        "admin_ward": "E05004064",
                        "parish": "E04003939",
                        "ccg": "E38000106"
                    }
                },
                {
                    "postcode": "CM8 1EU",
                    "quality": 1,
                    "eastings": 581507,
                    "northings": 213650,
                    "country": "England",
                    "nhs_ha": "East of England",
                    "longitude": 0.630485817275861,
                    "latitude": 51.7920493205979,
                    "parliamentary_constituency": "Witham",
                    "european_electoral_region": "Eastern",
                    "primary_care_trust": "Mid Essex",
                    "region": "East of England",
                    "lsoa": "Braintree 017F",
                    "msoa": "Braintree 017",
                    "nuts": null,
                    "incode": "1EU",
                    "outcode": "CM8",
                    "distance": 54.3765579,
                    "admin_district": "Braintree",
                    "parish": "Witham",
                    "admin_county": "Essex",
                    "admin_ward": "Witham South",
                    "ccg": "NHS Mid Essex",
                    "codes": {
                        "admin_district": "E07000067",
                        "admin_county": "E10000012",
                        "admin_ward": "E05004064",
                        "parish": "E04003939",
                        "ccg": "E38000106"
                    }
                },
                {
                    "postcode": "CM8 1PH",
                    "quality": 1,
                    "eastings": 581420,
                    "northings": 213741,
                    "country": "England",
                    "nhs_ha": "East of England",
                    "longitude": 0.629273287180607,
                    "latitude": 51.7928948417687,
                    "parliamentary_constituency": "Witham",
                    "european_electoral_region": "Eastern",
                    "primary_care_trust": "Mid Essex",
                    "region": "East of England",
                    "lsoa": "Braintree 017H",
                    "msoa": "Braintree 017",
                    "nuts": null,
                    "incode": "1PH",
                    "outcode": "CM8",
                    "distance": 74.327967941,
                    "admin_district": "Braintree",
                    "parish": "Witham",
                    "admin_county": "Essex",
                    "admin_ward": "Witham South",
                    "ccg": "NHS Mid Essex",
                    "codes": {
                        "admin_district": "E07000067",
                        "admin_county": "E10000012",
                        "admin_ward": "E05004064",
                        "parish": "E04003939",
                        "ccg": "E38000106"
                    }
                },
                {
                    "postcode": "CM8 1PQ",
                    "quality": 1,
                    "eastings": 581403,
                    "northings": 213752,
                    "country": "England",
                    "nhs_ha": "East of England",
                    "longitude": 0.629032807022633,
                    "latitude": 51.7929991478552,
                    "parliamentary_constituency": "Witham",
                    "european_electoral_region": "Eastern",
                    "primary_care_trust": "Mid Essex",
                    "region": "East of England",
                    "lsoa": "Braintree 017H",
                    "msoa": "Braintree 017",
                    "nuts": null,
                    "incode": "1PQ",
                    "outcode": "CM8",
                    "distance": 93.233290245,
                    "admin_district": "Braintree",
                    "parish": "Witham",
                    "admin_county": "Essex",
                    "admin_ward": "Witham South",
                    "ccg": "NHS Mid Essex",
                    "codes": {
                        "admin_district": "E07000067",
                        "admin_county": "E10000012",
                        "admin_ward": "E05004064",
                        "parish": "E04003939",
                        "ccg": "E38000106"
                    }
                },
                {
                    "postcode": "CM8 1EN",
                    "quality": 1,
                    "eastings": 581366,
                    "northings": 213664,
                    "country": "England",
                    "nhs_ha": "East of England",
                    "longitude": 0.628450923709479,
                    "latitude": 51.7922207606932,
                    "parliamentary_constituency": "Witham",
                    "european_electoral_region": "Eastern",
                    "primary_care_trust": "Mid Essex",
                    "region": "East of England",
                    "lsoa": "Braintree 016A",
                    "msoa": "Braintree 016",
                    "nuts": null,
                    "incode": "1EN",
                    "outcode": "CM8",
                    "distance": 96.173711876,
                    "admin_district": "Braintree",
                    "parish": "Witham",
                    "admin_county": "Essex",
                    "admin_ward": "Witham South",
                    "ccg": "NHS Mid Essex",
                    "codes": {
                        "admin_district": "E07000067",
                        "admin_county": "E10000012",
                        "admin_ward": "E05004064",
                        "parish": "E04003939",
                        "ccg": "E38000106"
                    }
                }
            ]
        },
        {
            "query": {
                "longitude": "-2.49690382054704",
                "latitude": "53.5351312861402",
                "radius": "1000",
                "limit": "5"
            },
            "result": [
                {
                    "postcode": "M46 9WU",
                    "quality": 1,
                    "eastings": 367163,
                    "northings": 404390,
                    "country": "England",
                    "nhs_ha": "North West",
                    "longitude": -2.49690382054704,
                    "latitude": 53.5351312861402,
                    "parliamentary_constituency": "Bolton West",
                    "european_electoral_region": "North West",
                    "primary_care_trust": "Ashton, Leigh and Wigan",
                    "region": "North West",
                    "lsoa": "Wigan 017C",
                    "msoa": "Wigan 017",
                    "nuts": null,
                    "incode": "9WU",
                    "outcode": "M46",
                    "distance": 0,
                    "admin_district": "Wigan",
                    "parish": null,
                    "admin_county": null,
                    "admin_ward": "Atherton",
                    "ccg": "NHS Wigan Borough",
                    "codes": {
                        "admin_district": "E08000010",
                        "admin_county": "E99999999",
                        "admin_ward": "E05000845",
                        "parish": "E43000164",
                        "ccg": "E38000205"
                    }
                },
                {
                    "postcode": "M46 9XF",
                    "quality": 1,
                    "eastings": 367155,
                    "northings": 404364,
                    "country": "England",
                    "nhs_ha": "North West",
                    "longitude": -2.49702177870104,
                    "latitude": 53.5348970961396,
                    "parliamentary_constituency": "Bolton West",
                    "european_electoral_region": "North West",
                    "primary_care_trust": "Ashton, Leigh and Wigan",
                    "region": "North West",
                    "lsoa": "Wigan 017B",
                    "msoa": "Wigan 017",
                    "nuts": null,
                    "incode": "9XF",
                    "outcode": "M46",
                    "distance": 27.21263663,
                    "admin_district": "Wigan",
                    "parish": null,
                    "admin_county": null,
                    "admin_ward": "Atherton",
                    "ccg": "NHS Wigan Borough",
                    "codes": {
                        "admin_district": "E08000010",
                        "admin_county": "E99999999",
                        "admin_ward": "E05000845",
                        "parish": "E43000164",
                        "ccg": "E38000205"
                    }
                },
                {
                    "postcode": "M46 9XE",
                    "quality": 1,
                    "eastings": 367212,
                    "northings": 404330,
                    "country": "England",
                    "nhs_ha": "North West",
                    "longitude": -2.49615824852127,
                    "latitude": 53.5345950752176,
                    "parliamentary_constituency": "Bolton West",
                    "european_electoral_region": "North West",
                    "primary_care_trust": "Ashton, Leigh and Wigan",
                    "region": "North West",
                    "lsoa": "Wigan 017C",
                    "msoa": "Wigan 017",
                    "nuts": null,
                    "incode": "9XE",
                    "outcode": "M46",
                    "distance": 77.493899852,
                    "admin_district": "Wigan",
                    "parish": null,
                    "admin_county": null,
                    "admin_ward": "Atherton",
                    "ccg": "NHS Wigan Borough",
                    "codes": {
                        "admin_district": "E08000010",
                        "admin_county": "E99999999",
                        "admin_ward": "E05000845",
                        "parish": "E43000164",
                        "ccg": "E38000205"
                    }
                },
                {
                    "postcode": "M46 9NX",
                    "quality": 1,
                    "eastings": 367245,
                    "northings": 404384,
                    "country": "England",
                    "nhs_ha": "North West",
                    "longitude": -2.49566605398193,
                    "latitude": 53.5350824929658,
                    "parliamentary_constituency": "Bolton West",
                    "european_electoral_region": "North West",
                    "primary_care_trust": "Ashton, Leigh and Wigan",
                    "region": "North West",
                    "lsoa": "Wigan 017C",
                    "msoa": "Wigan 017",
                    "nuts": null,
                    "incode": "9NX",
                    "outcode": "M46",
                    "distance": 82.248621381,
                    "admin_district": "Wigan",
                    "parish": null,
                    "admin_county": null,
                    "admin_ward": "Atherton",
                    "ccg": "NHS Wigan Borough",
                    "codes": {
                        "admin_district": "E08000010",
                        "admin_county": "E99999999",
                        "admin_ward": "E05000845",
                        "parish": "E43000164",
                        "ccg": "E38000205"
                    }
                },
                {
                    "postcode": "M46 9NU",
                    "quality": 1,
                    "eastings": 367171,
                    "northings": 404476,
                    "country": "England",
                    "nhs_ha": "North West",
                    "longitude": -2.49679217687234,
                    "latitude": 53.5359047567838,
                    "parliamentary_constituency": "Bolton West",
                    "european_electoral_region": "North West",
                    "primary_care_trust": "Ashton, Leigh and Wigan",
                    "region": "North West",
                    "lsoa": "Wigan 017C",
                    "msoa": "Wigan 017",
                    "nuts": null,
                    "incode": "9NU",
                    "outcode": "M46",
                    "distance": 86.402118746,
                    "admin_district": "Wigan",
                    "parish": null,
                    "admin_county": null,
                    "admin_ward": "Atherton",
                    "ccg": "NHS Wigan Borough",
                    "codes": {
                        "admin_district": "E08000010",
                        "admin_county": "E99999999",
                        "admin_ward": "E05000845",
                        "parish": "E43000164",
                        "ccg": "E38000205"
                    }
                }
            ]
        }
    ]
}
         */
    }
}